// <auto-generated />
namespace Stanford.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class initial1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial1));
        
        string IMigrationMetadata.Id
        {
            get { return "201505091745157_initial1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
